### ISSUE TITLE
gcc 7.3.0 produces code that can cause address errors for -m68000

### ISSUE THREAD

**Issue by th-otto** [freemint/m68k-atari-mint-gcc#9] opened 2018-10-20 14:55 UTC
The current version sometimes produces accesses to odd address, that would cause an address-error on plain 68000. The culprit seems to be https://github.com/freemint/m68k-atari-mint-gcc/blob/45f50048599322ca2c4bd34420b992c113195e72/gcc/config/m68k/mint.h#L23-L26

Simple test case:

```
void test(int c, char *p)
{
        *p++ = 'A' + c;
        *p++ = ':';
        *p = '\0';
}
```

produces

```
_test:
        move.l 8(%sp),%a0
        move.b 7(%sp),%d0
        add.b #65,%d0
        move.b %d0,(%a0)
        move.w #14848,1(%a0)
        rts
```

Similar code can also been found in EmuTOS https://github.com/emutos/emutos/blob/ec5bc814419255a1b1ac6e43543ef30589639144/aes/gemshlib.c#L98

Removing those lines would fix that, but also turn off that optimization for 020+

The generated code would then look like

```
_test:
        move.l 8(%sp),%a0
        move.b 7(%sp),%d0
        add.b #65,%d0
        move.b %d0,(%a0)
        move.b #58,1(%a0)
        clr.b 2(%a0)
        rts
```

I'm not sure what is better on 020: writing a word to an odd address, or writing 2 bytes instead?

I also could not convince gcc to use (a0)+ instead.

**Comment by vinriviere** [comment] 2018-10-20 16:14
What is "current version"? We have several branches.

**Comment by th-otto** [comment] 2018-10-20 16:19
The gcc-7-mint branch, which was used by Miro to build the native compilers.

**Comment by mikrosk** [comment] 2018-10-21 07:54
> I'm not sure what is better on 020: writing a word to an odd address, or writing 2 bytes instead?

Surely one word on an odd address. Unfortunately http://brownbot.mooo.com seems to be broken right now (@ggnkua do you know about it?) so I can't test other compilers how they handle 68000 vs. 68020.

**Comment by vinriviere** [comment] 2018-10-21 08:55
Test with: `...gcc -m68000 -O2 -fomit-frame-pointer -S a.c -o -`

m68k-atari-mint-gcc 4.6.4 produces the right thing: exactly "The generated code would then look like" above, without move.w.

Standard m68k-elf-gcc 7.1.0 also produces the exact same code.

And in any case, if I replace -m68000 by any other CPU options, the result stays the same: always good.

**Comment by ggnkua** [comment] 2018-10-21 08:59
> > I'm not sure what is better on 020: writing a word to an odd address, or writing 2 bytes instead?
> 
> Surely one word on an odd address. Unfortunately http://brownbot.mooo.com seems to be broken right now (@ggnkua do you know about it?) so I can't test other compilers how they handle 68000 vs. 68020.

Cannot reproduce here either. I get code snippet 2. If anyone wants to play around, http://brownbot.mooo.com/z/T6z_ao

**Comment by mikrosk** [comment] 2018-10-21 10:15
@ggnkua sorry, I should have been more specific - I meant that I got only a blank screen (no output) for the compiled code. seems to be working now and yes, your ELF build seems to be all right as well.

**Comment by mikrosk** [comment] 2018-10-21 10:18
I confirm @vinriviere findings - it seems that the right thing to do is to ignore this optimisation, i.e. always produce the 68000 version. Does disabling `STRICT_ALIGNMENT` have some other side effects?

**Comment by mikrosk** [comment] 2018-11-20 09:14
Fixed by https://github.com/freemint/m68k-atari-mint-gcc/commit/4b7a290df1a088933a94510aa50a6e0edea90469, will prepare a new release.

**Closed by mikrosk** 2018-11-20 09:14 UTC
